install:
  - java -version; mvn --show-version clean

language: java
jdk:
  - openjdk8
  - openjdk11
  
addons:
  sonarcloud:
    organization: "semsonar" 
    token: "$SONAR_TOKEN" 
    
script: mvn clean verify -Dcheckstyle.skip -Dpmd.skip=true sonar:sonar -Pcoverage -Dsonar.projectKey=$SONAR_TOKEN
  
#script: mvn test

cache:
 directories:
  - $HOME/.m2
