server:
  port: 8080
  servlet-path: /system

cxf:
  path: /services/helloservice
  servlet.init: 
    service-list-path: /info
  jaxrs:
    component-scan: true
    classes-scan-packages: org.apache.cxf.jaxrs.swagger

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    statusPageUrlPath: /services/helloservice/info
    healthCheckUrlPath: /system/health
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}} 
      servletPath: ${cxf.path}

