name: "Build and Test"

on:
  pull_request:
    branches: ['main', '3.6.x-fixes', '3.5.x-fixes', '3.4.x-fixes']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  
      pull-requests: read
    timeout-minutes: 130
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v3.6.0
      - name: Set up JDK 17
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Apache Maven
        run: mvn -U clean install -Djava.awt.headless=true -fae -B -Peverything
    env: 
       MAVEN_OPTS: "-Xmx1024M"
