name: "Build and Test"

on:
  pull_request:
    branches: ['main', '3.6.x-fixes', '3.5.x-fixes', '3.4.x-fixes']

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] 
    permissions:
      contents: read  
      pull-requests: read
    timeout-minutes: 130
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v3.6.0
      - name: Set up JDK 17
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4.3.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Apache Maven (Windows)
        if: ${{ matrix.os == 'windows-latest' }} 
        run: mvn -U clean install -fae -B -Peverything
      - name: Build with Apache Maven
        if: ${{ matrix.os != 'windows-latest' }} 
        run: mvn -U clean install -Djava.awt.headless=true -fae -B -Peverything
    env: 
       MAVEN_OPTS: "-Xmx1024M"
