name: "Build and Test"

on:
  pull_request:
    branches: ['3.5.x-fixes']

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] 
    permissions:
      contents: read  
      pull-requests: read
    timeout-minutes: 130
    steps:
      - uses: aactions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK 8
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Apache Maven (Windows)
        if: ${{ matrix.os == 'windows-latest' }} 
        run: mvn -U clean install -fae -B -Peverything
      - name: Build with Apache Maven
        if: ${{ matrix.os != 'windows-latest' }} 
        run: mvn -U clean install -Djava.awt.headless=true -fae -B -Peverything
    env: 
       MAVEN_OPTS: "-Xmx1024M"
