name: "Build and Test"

on:
  pull_request:
    branches: ['main', '3.6.x-fixes', '3.5.x-fixes', '3.4.x-fixes']

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] 
    permissions:
      contents: read  
      pull-requests: read
    timeout-minutes: 130
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v3.6.0
      - name: Set up JDK 17
        uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Apache Maven (Windows)
        if: ${{ matrix.os == 'windows-latest' }} 
        run: mvn -U clean install -fae -B -Peverything
      - name: Build with Apache Maven
        if: ${{ matrix.os != 'windows-latest' }} 
        run: mvn -U clean install -Djava.awt.headless=true -fae -B -Peverything
    env: 
       MAVEN_OPTS: "-Xmx1024M"
